### ISSUE TITLE
Mac OSX stack trace running example with 7.5

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j-kernels#3]
jcuda.CudaException: CUDA_ERROR_INVALID_CONTEXT
	at jcuda.driver.JCudaDriver.checkResult(JCudaDriver.java:326) ~[nd4j-jcublas-7.5-0.4-rc3.7-SNAPSHOT.jar:na]
	at jcuda.driver.JCudaDriver.cuStreamCreate(JCudaDriver.java:12328) ~[nd4j-jcublas-7.5-0.4-rc3.7-SNAPSHOT.jar:na]
	at org.nd4j.linalg.jcublas.context.pool.factory.StreamItemFactory.create(StreamItemFactory.java:23) ~[nd4j-jcublas-7.5-0.4-rc3.7-SNAPSHOT.jar:na]
	at org.nd4j.linalg.jcublas.context.pool.factory.StreamItemFactory.create(StreamItemFactory.java:19) ~[nd4j-jcublas-7.5-0.4-rc3.7-SNAPSHOT.jar:na]
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:60) ~[commons-pool2-2.4.2.jar:2.4.2]
o.n.l.j.k.KernelFunctionLoader - Error loading modules...attempting recompile
o.n.l.j.k.KernelFunctionLoader - Compiling cuda kernels
o.n.l.j.k.KernelFunctionLoader - Loading std_strided
java.lang.RuntimeException: java.lang.IllegalStateException: Unable to find path /tmp/nd4j-kernels/output/std_strided.cubin. Recompiling
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:272)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:269)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:200)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.load(KernelFunctionLoader.java:167)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.getInstance(KernelFunctionLoader.java:76)
	at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:92)
	at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:47)
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<init>(JCudaExecutioner.java:56)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4551)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4499)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:140)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:400)
	at org.deeplearning4j.examples.convolution.sampleNetStructure.AlexNet.init(AlexNet.java:58)
	at org.deeplearning4j.examples.convolution.CNNImageNetExample.main(CNNImageNetExample.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.IllegalStateException: Unable to find path /tmp/nd4j-kernels/output/std_strided.cubin. Recompiling
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.loadModules(KernelFunctionLoader.java:285)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:261)
	... 23 more
o.n.l.j.k.KernelFunctionLoader - Registering cuda functions...
o.n.l.j.k.KernelFunctionLoader - Compiling cuda kernels
o.n.l.j.k.KernelFunctionLoader - Loading std_strided
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<init>(JCudaExecutioner.java:56)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4551)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4499)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:140)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:400)
	at org.deeplearning4j.examples.convolution.sampleNetStructure.AlexNet.init(AlexNet.java:58)
	at org.deeplearning4j.examples.convolution.CNNImageNetExample.main(CNNImageNetExample.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Unable to find path /tmp/nd4j-kernels/output/std_strided.cubin. Recompiling
	at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:49)
	... 17 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Unable to find path /tmp/nd4j-kernels/output/std_strided.cubin. Recompiling
	at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:94)
	at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:47)
	... 17 more
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Unable to find path /tmp/nd4j-kernels/output/std_strided.cubin. Recompiling
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:272)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:200)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.load(KernelFunctionLoader.java:167)
	at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:92)
	... 18 more
Caused by: java.lang.IllegalStateException: Unable to find path /tmp/nd4j-kernels/output/std_strided.cubin. Recompiling
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.loadModules(KernelFunctionLoader.java:285)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:261)
	... 21 more

Process finished with exit code 1

**Comment by NathanHowell** [comment]
For some reason there are duplicate classes (with different behavior) in `nd4j-jcublas-7.5` and `nd4j-jcublas-common`. The 7.5 version of `org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader` seems to cause this particular issue. I've hacked around it with this patch, but I'd imagine deleting the class might work too :disappointed: 

```diff
diff --git a/nd4j-jcublas-parent/nd4j-jcublas-7.5/src/main/java/org/nd4j/linalg/jcublas/kernel/KernelFunctionLoader.java b/nd4j-jcublas-parent/nd4j-jcublas-7.5/src/main/java/org/nd4j/linalg/jcublas/kernel/KernelFunctionLoader.java
index f1d7e44..803d2e1 100644
--- a/nd4j-jcublas-parent/nd4j-jcublas-7.5/src/main/java/org/nd4j/linalg/jcublas/kernel/KernelFunctionLoader.java
+++ b/nd4j-jcublas-parent/nd4j-jcublas-7.5/src/main/java/org/nd4j/linalg/jcublas/kernel/KernelFunctionLoader.java
@@ -345,7 +345,7 @@ public class KernelFunctionLoader {


     private void loadCudaKernels() throws IOException {
-        Set<String> resources = new Reflections("org.nd4j.nd4j-kernels", new ResourcesScanner()).getResources(Pattern.compile(".*"));
+        Set<String> resources = new Reflections("kernels", new ResourcesScanner()).getResources(Pattern.compile(".*"));
         for(String resource : resources) {
             extract(resource);
         }
```
